import wixLocationFrontend from "wix-location-frontend";
import wixLocation from 'wix-location';
import wixData from "wix-data";


$w.onReady(function () {
    // Set the payment ID (this should be generated by your backend/payment processing logic)
    let object = wixLocationFrontend.query;
    let addresses = object.address;
    let price  = object.price;
    const dataset = "Blockonomics_order";

    console.log("New Address:", addresses);
         console.log ("Price:",  price );

     $w("#input1").value = addresses; 
     $w("#input2").value = price; 





    // Set up the payment button click event
    $w("#button1").onClick((event) => {
        wixLocation.to(object.redirect);
    });
});
